name: smart_farming_web
description: Application Smart Farming avec simulation de données

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  
  # UI Components
  syncfusion_flutter_gauges: ^24.1.41
  
  # HTTP requests
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true